using DonationFraud.API.Middleware;
using DonationFraud.API.Interfaces;
using DonationFraud.API.FraudEngine;
using DonationFraud.API.Data;
using DonationFraud.API.Repositories;
using DonationFraud.API.Services;
using DonationFraud.API.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.IdentityModel.Tokens;
using Microsoft.OpenApi.Models;
using Serilog;
using System.Text;
using Scalar.AspNetCore;

var builder = WebApplication.CreateBuilder(args);

// 1. Configure Serilog
Log.Logger = new LoggerConfiguration()
    .ReadFrom.Configuration(builder.Configuration)
    .Enrich.FromLogContext()
    .WriteTo.Console()
    .WriteTo.File("logs/log-.txt", rollingInterval: RollingInterval.Day)
    .CreateLogger();

builder.Host.UseSerilog();

// 2. Add Database Context
if (!builder.Environment.IsEnvironment("Testing"))
{
    builder.Services.AddDbContext<DonationDbContext>(options =>
        options.UseSqlServer(builder.Configuration.GetConnectionString("DefaultConnection")));
}

// 3. Add Authentication & JWT
var jwtKey = builder.Configuration["JwtSettings:Secret"] ?? "SuperSecretKeyForDonationFraudSystem123!";
var jwtIssuer = builder.Configuration["JwtSettings:Issuer"];
var jwtAudience = builder.Configuration["JwtSettings:Audience"];

builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuer = true,
            ValidateAudience = true,
            ValidateLifetime = true,
            ValidateIssuerSigningKey = true,
            ValidIssuer = jwtIssuer,
            ValidAudience = jwtAudience,
            IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtKey))
        };
    });

// 4. Register Dependencies
// Repositories
builder.Services.AddScoped<IUserRepository, UserRepository>();
builder.Services.AddScoped<ICampaignRepository, CampaignRepository>();
builder.Services.AddScoped<IDonationRepository, DonationRepository>();
builder.Services.AddScoped<IFraudFlagRepository, FraudFlagRepository>();

// Services
builder.Services.AddScoped<IAuthService, AuthService>();
builder.Services.AddScoped<ICampaignService, CampaignService>();
builder.Services.AddScoped<IDonationService, DonationService>();
builder.Services.AddScoped<IFraudManagementService, FraudManagementService>();
builder.Services.AddScoped<IFraudDetectionService, FraudDetectionService>();
builder.Services.AddScoped<IAuditService, AuditService>();

// Fraud Engine
builder.Services.AddScoped<IFraudEvaluator, FraudEvaluator>();
builder.Services.AddScoped<IFraudRule, HighFrequencyRule>();
builder.Services.AddScoped<IFraudRule, SpikeRule>();
builder.Services.AddScoped<IFraudRule, SameIPRule>();

builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();

// 6. Add CORS for Angular Frontend
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowAngularFrontend", policy =>
    {
        policy.WithOrigins(
                "http://localhost:4200",    // Angular dev server
                "https://localhost:4200"
            )
            .AllowAnyHeader()
            .AllowAnyMethod()
            .AllowCredentials();
    });

    // Permissive policy for development — allows any origin
    options.AddPolicy("AllowAll", policy =>
    {
        policy.AllowAnyOrigin()
            .AllowAnyHeader()
            .AllowAnyMethod();
    });
});

// 5. Swagger with JWT Support
builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "Donation Fraud API", Version = "v1" });
    c.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
    {
        Description = "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\"",
        Name = "Authorization",
        In = ParameterLocation.Header,
        Type = SecuritySchemeType.ApiKey,
        Scheme = "Bearer"
    });

    c.AddSecurityRequirement(new OpenApiSecurityRequirement()
    {
        {
            new OpenApiSecurityScheme
            {
                Reference = new OpenApiReference
                {
                    Type = ReferenceType.SecurityScheme,
                    Id = "Bearer"
                },
                Scheme = "oauth2",
                Name = "Bearer",
                In = ParameterLocation.Header,
            },
            new List<string>()
        }
    });
});

var app = builder.Build();

// Configure the HTTP request pipeline.
app.UseSwagger();
// app.UseSwaggerUI();

app.MapScalarApiReference(options => 
{
    // Tell Scalar where to find the Swagger JSON generated by Swashbuckle
    options.WithOpenApiRoutePattern("/swagger/{documentName}/swagger.json");
});

// Redirect root and /scalar to the actual Scalar UI endpoint for convenience
app.MapGet("/", () => Results.Redirect("/scalar/v1"));
app.MapGet("/scalar", () => Results.Redirect("/scalar/v1"));

app.UseMiddleware<GlobalExceptionHandlingMiddleware>();

app.UseHttpsRedirection();

// Use CORS — must be before UseAuthentication/UseAuthorization
if (app.Environment.IsDevelopment())
{
    app.UseCors("AllowAll");
}
else
{
    app.UseCors("AllowAngularFrontend");
}

app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();

using (var scope = app.Services.CreateScope())
{
    var dbContext = scope.ServiceProvider.GetRequiredService<DonationDbContext>();
    
    try
    {
        // Apply migrations or create DB
        dbContext.Database.Migrate();

        // Perform a quick check to see if the schema is healthy and has IsActive column
        _ = dbContext.Campaigns.Select(c => c.IsActive).FirstOrDefault();
    }
    catch (Exception ex)
    {
        Console.WriteLine($"Database schema mismatch detected: {ex.Message}. Recreating database to sync schema...");
        dbContext.Database.EnsureDeleted();
        dbContext.Database.Migrate();
    }

    if (!dbContext.FraudRuleConfigs.Any())
    {
        dbContext.FraudRuleConfigs.AddRange(
            new DonationFraud.API.Entities.FraudRuleConfig { RuleName = "HighFrequency", Threshold = 3, RiskScoreContribution = 40, IsActive = true },
            new DonationFraud.API.Entities.FraudRuleConfig { RuleName = "SameIP", Threshold = 5, RiskScoreContribution = 20, IsActive = true },
            new DonationFraud.API.Entities.FraudRuleConfig { RuleName = "SpikeAmount", Threshold = 10000, RiskScoreContribution = 70, IsActive = true }
        );
        dbContext.SaveChanges();
    }

    var userRepo = scope.ServiceProvider.GetRequiredService<IUserRepository>();
    var adminExists = await userRepo.GetUserByUsernameAsync("admin@mail.com");
    if (adminExists == null)
    {
        var authService = scope.ServiceProvider.GetRequiredService<IAuthService>();
        await authService.RegisterAsync(new DonationFraud.API.DTOs.RegisterRequestDto
        {
            Username = "admin@mail.com",
            Email = "admin@mail.com",
            FirstName = "System",
            LastName = "Admin",
            Password = "admin",
            Role = "Admin"
        });
    }

    var donorExists = await userRepo.GetUserByUsernameAsync("donor@mail.com");
    User donorUser;
    if (donorExists == null)
    {
        var authService = scope.ServiceProvider.GetRequiredService<IAuthService>();
        await authService.RegisterAsync(new DonationFraud.API.DTOs.RegisterRequestDto
        {
            Username = "donor@mail.com",
            Email = "donor@mail.com",
            FirstName = "John",
            LastName = "Doe",
            Password = "password",
            Role = "User"
        });
        donorUser = await userRepo.GetUserByUsernameAsync("donor@mail.com") 
            ?? throw new InvalidOperationException("Failed to register donor user.");
    }
    else
    {
        donorUser = donorExists;
    }

    if (!dbContext.Campaigns.Any())
    {
        var campaign1 = new Campaign
        {
            Title = "Save the Amazon Rainforest",
            Description = "Help us plant trees and protect wildlife.",
            TargetAmount = 50000,
            IsActive = true
        };
        var campaign2 = new Campaign
        {
            Title = "Clean Water Initiative",
            Description = "Providing clean water to remote villages.",
            TargetAmount = 25000,
            IsActive = true
        };
        var campaign3 = new Campaign
        {
            Title = "Ended Scholarship Fund",
            Description = "Providing tuition fees for underprivileged students.",
            TargetAmount = 10000,
            IsActive = false
        };

        dbContext.Campaigns.AddRange(campaign1, campaign2, campaign3);
        await dbContext.SaveChangesAsync();

        // Seed some donations for campaign3
        var donation1 = new Donation
        {
            CampaignId = campaign3.Id,
            UserId = donorUser.Id,
            Amount = 5000,
            Timestamp = DateTime.UtcNow.AddDays(-5),
            IpAddress = "127.0.0.1"
        };
        var donation2 = new Donation
        {
            CampaignId = campaign3.Id,
            UserId = donorUser.Id,
            Amount = 5000,
            Timestamp = DateTime.UtcNow.AddDays(-4),
            IpAddress = "127.0.0.1"
        };

        dbContext.Donations.AddRange(donation1, donation2);
        await dbContext.SaveChangesAsync();
    }
}

app.Run();

public partial class Program { }
